'use client';

import { useMemo, useState } from 'react';
import { ArrowRight, CalendarClock, Download, Mail, Plus, Search, TrendingUp } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';

const arRows = [
  { party: 'Aurora Hospitality', invoice: 'NS-INV-2039', issued: '26 Jul 2026', due: '25 Aug 2026', amount: '$18,600', balance: '$18,600', days: 3, status: 'Overdue', owner: 'Evan Ross' },
  { party: 'Westhaven Foods', invoice: 'NS-INV-2042', issued: '02 Aug 2026', due: '01 Sep 2026', amount: '$32,400', balance: '$32,400', days: 0, status: 'Pending', owner: 'Evan Ross' },
  { party: 'Solace Health Group', invoice: 'NS-INV-2035', issued: '25 Jul 2026', due: '24 Aug 2026', amount: '$31,200', balance: '$0', days: 0, status: 'Paid', owner: 'Mina Park' },
  { party: 'Northline Retail Co.', invoice: 'NS-INV-2048', issued: '12 Aug 2026', due: '11 Sep 2026', amount: '$24,800', balance: '$12,400', days: 0, status: 'Partially Paid', owner: 'Evan Ross' },
  { party: 'Cedar & Stone', invoice: 'NS-INV-2014', issued: '18 Jun 2026', due: '18 Jul 2026', amount: '$14,750', balance: '$14,750', days: 41, status: 'Overdue', owner: 'Sofia Chen' },
];
const apRows = [
  { party: 'Arden Cloud Services', invoice: 'INV-ACS-8821', issued: '21 Aug 2026', due: '31 Aug 2026', amount: '$8,420', balance: '$8,420', days: 0, status: 'Pending Approval', owner: 'Mina Park' },
  { party: 'Juniper Logistics', invoice: 'JL-44710', issued: '20 Aug 2026', due: '03 Sep 2026', amount: '$6,284', balance: '$6,284', days: 0, status: 'Scheduled', owner: 'Mina Park' },
  { party: 'Blue Ridge Facilities', invoice: 'BR-1811', issued: '10 Aug 2026', due: '25 Aug 2026', amount: '$12,480', balance: '$0', days: 0, status: 'Paid', owner: 'Jordan Lee' },
  { party: 'Fieldstone Studio', invoice: 'FS-0927', issued: '11 Aug 2026', due: '26 Aug 2026', amount: '$3,950', balance: '$3,950', days: 2, status: 'Overdue', owner: 'Sofia Chen' },
  { party: 'Meridian Legal', invoice: 'ML-2088', issued: '18 Aug 2026', due: '07 Sep 2026', amount: '$9,600', balance: '$9,600', days: 0, status: 'Under Review', owner: 'Jordan Lee' },
];
const styles: Record<string, string> = { Paid: 'border-emerald-200 bg-emerald-50 text-emerald-700', Pending: 'border-amber-200 bg-amber-50 text-amber-700', Overdue: 'border-red-200 bg-red-50 text-red-700', 'Partially Paid': 'border-violet-200 bg-violet-50 text-violet-700', 'Pending Approval': 'border-amber-200 bg-amber-50 text-amber-700', Scheduled: 'border-sky-200 bg-sky-50 text-sky-700', 'Under Review': 'border-slate-200 bg-slate-50 text-slate-700' };

export function LedgerModule({ kind }: { kind: 'ar' | 'ap' }) {
  const ar = kind === 'ar'; const rows = ar ? arRows : apRows;
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('All');
  const filtered = useMemo(() => rows.filter((r) => `${r.party} ${r.invoice}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'All' || r.status === filter)), [rows, query, filter]);
  const title = ar ? 'Accounts receivable' : 'Accounts payable';
  return <div className="space-y-5">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="mb-1 text-xs text-muted-foreground">Finance / {ar ? 'Receivables' : 'Payables'}</p><h1 className="text-2xl font-semibold tracking-tight md:text-3xl">{title}</h1><p className="mt-1 text-sm text-muted-foreground">{ar ? 'Collect faster and keep every customer follow-up visible.' : 'Plan supplier payments and prevent late-payment risk.'}</p></div><div className="flex gap-2"><Button variant="outline" className="bg-card"><Download /> Export</Button><Button><Plus /> {ar ? 'New invoice' : 'Record bill'}</Button></div></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{(ar ? [['Outstanding','$78.2K','14 open invoices'],['Overdue','$33.4K','6 require follow-up'],['Due next 7 days','$44.8K','5 invoices'],['DSO','28 days','3 days better']] : [['Outstanding','$62.7K','17 open bills'],['Overdue','$3.95K','1 supplier'],['Due next 7 days','$31.2K','4 scheduled'],['On-time rate','96%','+2.1% this quarter']]).map(([label,value,note], i) => <Card key={label} className="gap-0"><CardContent className="p-5"><div className="flex items-center justify-between"><p className="text-xs text-muted-foreground">{label}</p>{i === 1 ? <CalendarClock className="size-4 text-red-500" /> : <TrendingUp className="size-4 text-primary" />}</div><p className="metric-value mt-2 text-2xl font-semibold">{value}</p><p className="mt-1 text-[11px] text-muted-foreground">{note}</p></CardContent></Card>)}</div>
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_340px]">
      <Card className="min-w-0 gap-0"><CardHeader className="border-b"><CardTitle>{ar ? 'Customer invoices' : 'Supplier invoices'}</CardTitle><CardDescription>{filtered.length} records in the current view</CardDescription></CardHeader><CardContent className="px-2 pb-2"><div className="flex flex-col gap-2 border-b p-3 md:flex-row"><div className="relative flex-1"><Search className="absolute left-2.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search party or invoice" className="h-9 pl-8" /></div><select value={filter} onChange={(e) => setFilter(e.target.value)} className="h-9 rounded-lg border bg-card px-3 text-sm"><option>All</option>{Array.from(new Set(rows.map((r) => r.status))).map((s) => <option key={s}>{s}</option>)}</select></div><Table><TableHeader><TableRow><TableHead>{ar ? 'Customer' : 'Vendor'}</TableHead><TableHead>Due</TableHead><TableHead>Status</TableHead><TableHead className="hidden md:table-cell">Owner</TableHead><TableHead className="text-right">Outstanding</TableHead></TableRow></TableHeader><TableBody>{filtered.map((row) => <TableRow key={row.invoice}><TableCell><p className="font-medium">{row.party}</p><p className="text-[11px] text-muted-foreground">{row.invoice} · {row.issued}</p></TableCell><TableCell><p>{row.due}</p>{row.days ? <p className="text-[11px] font-medium text-red-600">{row.days} days overdue</p> : null}</TableCell><TableCell><Badge variant="outline" className={styles[row.status]}>{row.status}</Badge></TableCell><TableCell className="hidden text-muted-foreground md:table-cell">{row.owner}</TableCell><TableCell className="text-right font-mono text-xs font-semibold">{row.balance}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
      <div className="space-y-4"><Card><CardHeader><CardTitle>{ar ? 'Receivable aging' : 'Payable aging'}</CardTitle><CardDescription>Open balance by age</CardDescription></CardHeader><CardContent className="space-y-4">{[['Current',56,'$43.8K'],['1–30 days',28,'$21.9K'],['31–60 days',12,'$9.4K'],['60+ days',4,'$3.1K']].map(([label,width,value]) => <div key={label as string}><div className="mb-1.5 flex justify-between text-xs"><span>{label}</span><span className="font-mono">{value}</span></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${width}%` }} /></div></div>)}</CardContent></Card><Card><CardHeader><CardTitle>{ar ? 'Collection queue' : 'Payment calendar'}</CardTitle><CardDescription>{ar ? 'Automated follow-up is active' : 'Reminders run before every due date'}</CardDescription></CardHeader><CardContent className="space-y-3"><div className="flex gap-3 rounded-xl bg-muted/45 p-3"><Mail className="mt-0.5 size-4 text-primary" /><div><p className="text-xs font-semibold">{ar ? '3 reminders due today' : '4 payments due this week'}</p><p className="mt-0.5 text-[11px] text-muted-foreground">Next automation run at 16:00</p></div></div><Button variant="outline" className="w-full">Open {ar ? 'follow-up tasks' : 'payment schedule'} <ArrowRight /></Button></CardContent></Card></div>
    </div>
  </div>;
}
