'use client';

import { useMemo, useState } from 'react';
import { ArrowLeftRight, CalendarDays, ChevronRight, Download, FileCheck2, Filter, Plus, Search, ShieldCheck } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';

const rows = [
  { id: 'TRX-2026-0841', date: '28 Aug 2026', type: 'Expense', reference: 'INV-ACS-8821', party: 'Arden Cloud Services', department: 'Technology', category: 'Software & subscriptions', amount: '$8,420.00', status: 'Pending', approval: 'Finance review', owner: 'Mina Park' },
  { id: 'TRX-2026-0840', date: '28 Aug 2026', type: 'Income', reference: 'NS-INV-2048', party: 'Northline Retail Co.', department: 'Commercial', category: 'Product revenue', amount: '$24,800.00', status: 'Paid', approval: 'Approved', owner: 'Evan Ross' },
  { id: 'TRX-2026-0839', date: '27 Aug 2026', type: 'Expense', reference: 'FS-0927', party: 'Fieldstone Studio', department: 'Marketing', category: 'Marketing services', amount: '$3,950.00', status: 'Missing Document', approval: 'Action required', owner: 'Sofia Chen' },
  { id: 'TRX-2026-0838', date: '27 Aug 2026', type: 'Expense', reference: 'JL-44710', party: 'Juniper Logistics', department: 'Operations', category: 'Freight & delivery', amount: '$6,284.00', status: 'Approved', approval: 'Approved', owner: 'Mina Park' },
  { id: 'TRX-2026-0837', date: '26 Aug 2026', type: 'Income', reference: 'NS-INV-2039', party: 'Aurora Hospitality', department: 'Commercial', category: 'Service revenue', amount: '$18,600.00', status: 'Overdue', approval: 'Approved', owner: 'Evan Ross' },
  { id: 'TRX-2026-0836', date: '25 Aug 2026', type: 'Expense', reference: 'BR-1811', party: 'Blue Ridge Facilities', department: 'Operations', category: 'Facilities', amount: '$12,480.00', status: 'Paid', approval: 'Approved', owner: 'Mina Park' },
  { id: 'TRX-2026-0835', date: '25 Aug 2026', type: 'Income', reference: 'NS-INV-2035', party: 'Solace Health Group', department: 'Commercial', category: 'Service revenue', amount: '$31,200.00', status: 'Paid', approval: 'Approved', owner: 'Evan Ross' },
];
const badgeStyles: Record<string, string> = { Paid: 'border-emerald-200 bg-emerald-50 text-emerald-700', Approved: 'border-sky-200 bg-sky-50 text-sky-700', Pending: 'border-amber-200 bg-amber-50 text-amber-700', Overdue: 'border-red-200 bg-red-50 text-red-700', 'Missing Document': 'border-orange-200 bg-orange-50 text-orange-700' };

export function TransactionsContent({ type = 'All' }: { type?: 'All' | 'Income' | 'Expense' }) {
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState('All statuses');
  const typeRows = useMemo(() => type === 'All' ? rows : rows.filter((row) => row.type === type), [type]);
  const [selected, setSelected] = useState(type === 'Expense' ? rows[0] : type === 'Income' ? rows[1] : rows[0]);
  const filtered = useMemo(() => typeRows.filter((row) => `${row.id} ${row.reference} ${row.party} ${row.category}`.toLowerCase().includes(query.toLowerCase()) && (status === 'All statuses' || row.status === status)), [typeRows, query, status]);
  const title = type === 'Income' ? 'Income register' : type === 'Expense' ? 'Expense register' : 'Transaction register';
  const copy = type === 'Income' ? 'Track recognized revenue, collections, and supporting invoices.' : type === 'Expense' ? 'Control operating spend, evidence, approvals, and payment status.' : 'Review, trace, and control all financial activity.';
  return (
    <div className="space-y-5">
      <div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="mb-1 text-xs text-muted-foreground">Finance / {type === 'All' ? 'Transactions' : type}</p><h1 className="text-2xl font-semibold tracking-tight md:text-3xl">{title}</h1><p className="mt-1 text-sm text-muted-foreground">{copy}</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" className="bg-card"><Download /> Export</Button><Button><Plus /> New {type === 'All' ? 'transaction' : type.toLowerCase()}</Button></div></div>
      <Card className="gap-0 shadow-[0_1px_2px_rgb(15_23_42/3%)]"><CardContent className="p-3"><div className="flex flex-col gap-2 md:flex-row"><div className="relative min-w-0 flex-1"><Search className="absolute left-2.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search ID, reference, counterparty or category" className="h-9 pl-8" /></div><select value={status} onChange={(e) => setStatus(e.target.value)} className="h-9 rounded-lg border bg-card px-3 text-sm outline-none focus:ring-2 focus:ring-ring/40"><option>All statuses</option><option>Paid</option><option>Pending</option><option>Approved</option><option>Overdue</option><option>Missing Document</option></select><Button variant="outline" className="h-9"><CalendarDays /> 1–31 Aug 2026</Button><Button variant="outline" className="h-9"><Filter /> More filters</Button></div></CardContent></Card>
      <div className="grid min-h-[590px] gap-4 xl:grid-cols-[minmax(0,1fr)_360px]">
        <Card className="min-w-0 gap-0 shadow-[0_1px_2px_rgb(15_23_42/3%)]"><CardHeader className="border-b py-4"><CardTitle className="flex items-center justify-between"><span>{filtered.length} transactions</span><span className="text-xs font-normal text-muted-foreground">Total visible: $105,734.00</span></CardTitle></CardHeader><CardContent className="px-2 pb-2"><Table><TableHeader><TableRow><TableHead>Transaction</TableHead><TableHead>Counterparty</TableHead><TableHead className="hidden lg:table-cell">Department</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Amount</TableHead><TableHead className="w-8" /></TableRow></TableHeader><TableBody>{filtered.map((row) => <TableRow key={row.id} onClick={() => setSelected(row)} data-state={selected.id === row.id ? 'selected' : undefined} className="cursor-pointer"><TableCell><p className="font-medium">{row.id}</p><p className="text-[11px] text-muted-foreground">{row.date} · {row.type}</p></TableCell><TableCell><p>{row.party}</p><p className="text-[11px] text-muted-foreground">{row.reference}</p></TableCell><TableCell className="hidden text-muted-foreground lg:table-cell">{row.department}</TableCell><TableCell><Badge variant="outline" className={badgeStyles[row.status]}>{row.status}</Badge></TableCell><TableCell className="text-right font-mono text-xs font-semibold">{row.amount}</TableCell><TableCell><ChevronRight className="size-4 text-muted-foreground" /></TableCell></TableRow>)}</TableBody></Table>{filtered.length === 0 ? <div className="grid min-h-56 place-items-center text-center"><div><Search className="mx-auto mb-2 size-7 text-muted-foreground" /><p className="font-medium">No matching transactions</p><p className="mt-1 text-sm text-muted-foreground">Adjust the search or status filter.</p></div></div> : null}</CardContent></Card>
        <Card className="h-fit gap-0 shadow-[0_1px_2px_rgb(15_23_42/3%)] xl:sticky xl:top-20"><CardHeader className="border-b py-4"><div><p className="text-[10px] font-semibold uppercase tracking-[0.13em] text-muted-foreground">Transaction detail</p><CardTitle className="mt-1">{selected.id}</CardTitle></div></CardHeader><CardContent className="space-y-5 p-5"><div className="flex items-start justify-between"><div><p className="text-xs text-muted-foreground">Total amount</p><p className="metric-value mt-1 text-2xl font-semibold">{selected.amount}</p></div><Badge variant="outline" className={badgeStyles[selected.status]}>{selected.status}</Badge></div><dl className="grid grid-cols-2 gap-x-4 gap-y-4 text-xs"><div><dt className="text-muted-foreground">Counterparty</dt><dd className="mt-1 font-medium">{selected.party}</dd></div><div><dt className="text-muted-foreground">Reference</dt><dd className="mt-1 font-medium">{selected.reference}</dd></div><div><dt className="text-muted-foreground">Department</dt><dd className="mt-1 font-medium">{selected.department}</dd></div><div><dt className="text-muted-foreground">Category</dt><dd className="mt-1 font-medium">{selected.category}</dd></div><div><dt className="text-muted-foreground">Responsible</dt><dd className="mt-1 font-medium">{selected.owner}</dd></div><div><dt className="text-muted-foreground">Approval</dt><dd className="mt-1 font-medium">{selected.approval}</dd></div></dl><div className="rounded-xl border bg-muted/30 p-3"><div className="flex items-center gap-2 text-xs font-semibold"><ArrowLeftRight className="size-4 text-primary" /> Balanced journal</div><div className="mt-3 flex justify-between text-xs"><span className="text-muted-foreground">Debit</span><span className="font-mono">{selected.amount}</span></div><div className="mt-2 flex justify-between text-xs"><span className="text-muted-foreground">Credit</span><span className="font-mono">{selected.amount}</span></div></div><div className="space-y-2"><div className="flex items-center gap-2 text-xs"><FileCheck2 className="size-4 text-emerald-600" /><span>2 supporting documents</span></div><div className="flex items-center gap-2 text-xs"><ShieldCheck className="size-4 text-emerald-600" /><span>Audit trail intact · 6 events</span></div></div><div className="grid grid-cols-2 gap-2"><Button variant="outline">View documents</Button><Button>Open record</Button></div></CardContent></Card>
      </div>
    </div>
  );
}
